using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LUSSIS_Backend;
using LUSSIS_Backend.model;
using LUSSIS_Backend.controller;

public partial class Store_Clerk_OrderFormUI : System.Web.UI.Page
{     // ATTRIBUTES

    List<OrderItem> orderList;
    List<StationeryCatalogue> stockList;
    List<Supplier> supplierList = OrderController.GetAllSuppliers();

    int orderedBy = 10;
    int approvedBy = 11;
    DateTime dateIssued = DateTime.Today;

    // METHODS

    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            // Set OrderList
            orderList = OrderController.GetAutoGeneratedOrderList();

            // Set StockList
            stockList = OrderController.GetStockList(orderList);

            // Load OrderList
            LoadOrderList(orderList);

            // Load StockList
            LoadStockList(stockList);

            // Load SupplierList
            LoadSupplierList(supplierList);
        }
    }

    protected void BlankButton_Click(object sender, EventArgs e)
    {
        // Set OrderList to Empty
        orderList = new List<OrderItem>();

        // Set StockList to All
        stockList = OrderController.GetAllStocks();

        // Load OrderList
        LoadOrderList(orderList);

        // Load StockList
        LoadStockList(stockList);
    }

    protected void AutoGenerateButton_Click(object sender, EventArgs e)
    {
        // Set OrderList
        orderList = OrderController.GetAutoGeneratedOrderList();

        // Set StockList
        stockList = OrderController.GetStockList(orderList);

        // Load OrderList
        LoadOrderList(orderList);

        // Load StockList
        LoadStockList(stockList);
    }

    protected void AddButton_Click(object sender, EventArgs e)
    {
        // Get OrderList from Page
        orderList = GetOrderListFromPage();

        // Add New Item to OrderList
        string itemNo = StockDropDownList.SelectedValue;
        if (!itemNo.Equals(""))
        {
            OrderController.AddOrder(orderList, itemNo);
        }

        // Get Stocklist
        stockList = OrderController.GetStockList(orderList);

        // Load OrderList
        LoadOrderList(orderList);

        // Load StockList
        LoadStockList(stockList);
    }

    protected void DeleteButton_Click(object sender, EventArgs e)
    {
        // Get OrderList from Page
        orderList = GetOrderListFromPage();

        // Delete item from OrderList
        string itemNo = GetDeletedItemNo(sender, e);
        for (int i = 0; i < orderList.Count; i++)
        {
            OrderItem oI = orderList[i];
            if (oI.ItemNo == itemNo)
            {
                orderList.Remove(oI);
                break;
            }
        }

        // Get Stocklist
        stockList = OrderController.GetStockList(orderList);

        // Load OrderList
        LoadOrderList(orderList);

        // Load StockList
        LoadStockList(stockList);
    }

    protected void SubmitButton_Click(object sender, EventArgs e)
    {
        // Get OrderList from Page
        orderList = GetOrderListFromPage();

        // Submit Order
        OrderController.SubmitOrder(orderList, orderedBy, approvedBy, dateIssued);

        // Redirect to SuccessPage
        Response.Redirect(successPageUrl);
    }

    protected void SupplierDropDownList_SelectedIndexChanged(object sender, EventArgs e)
    {
        if (!SupplierDropDownList.SelectedValue.Equals(""))
        {
            Supplier selectedSupplier = OrderController.GetSupplier(SupplierDropDownList.SelectedValue);
            SupplierTextBox.Text = selectedSupplier.ContactName;
            ContactTextBox.Text = selectedSupplier.PhoneNo.ToString();
        }
    }

    // PRIVATE METHODS

    private void LoadPage(List<OrderItem> orderList, List<StationeryCatalogue> stockList, List<Supplier> sList)
    {
        // Repeater
        Repeater1.DataSource = orderList;
        Repeater1.DataBind();

        // StockDropDownList
        StockDropDownList.DataValueField = "ItemNo";
        StockDropDownList.DataTextField = "Description";
        StockDropDownList.DataSource = stockList;
        StockDropDownList.DataBind();

        // SupplierDropDownList
        SupplierDropDownList.DataValueField = "SupplierCode";
        SupplierDropDownList.DataTextField = "SupplierName";
        SupplierDropDownList.DataSource = stockList;
        SupplierDropDownList.DataBind();
    }

    private List<OrderItem> GetOrderListFromPage()
    {
        orderList = new List<OrderItem>();
        RepeaterItemCollection items = Repeater1.Items;

        // For each Repeater Item
        for (int i = 0; i < items.Count; i++)
        {
            RepeaterItem rI = items[i];
            string itemNo = (rI.FindControl("ItemNoLabel") as Label).Text;
            StationeryCatalogue stock = OrderController.GetStock(itemNo);

            // Create OrderItem
            OrderItem oI = new OrderItem(stock);
            oI.Qty1 = Convert.ToInt32((rI.FindControl("Qty1TextBox") as TextBox).Text);
            oI.Qty2 = Convert.ToInt32((rI.FindControl("Qty2TextBox") as TextBox).Text);
            oI.Qty3 = Convert.ToInt32((rI.FindControl("Qty3TextBox") as TextBox).Text);

            orderList.Add(oI);
        }

        return orderList;
    }

    private string GetDeletedItemNo(object sender, EventArgs e)
    {
        Button b = (Button)sender;
        string itemNo = b.CommandArgument;
        return itemNo;
    }

    private void LoadOrderList(List<OrderItem> orderList)
    {
        orderList = orderList.OrderBy(x => x.ItemNo).ToList<OrderItem>();
        Repeater1.DataSource = orderList;
        Repeater1.DataBind();
    }

    private void LoadStockList(List<StationeryCatalogue> stockList)
    {
        StockDropDownList.DataValueField = "ItemNo";
        StockDropDownList.DataTextField = "Description";
        stockList.Insert(0, new StationeryCatalogue() { ItemNo = "", Description = "Select Item" });
        StockDropDownList.DataSource = stockList;
        StockDropDownList.DataBind();
    }

    private void LoadSupplierList(List<Supplier> supplierList)
    {
        SupplierDropDownList.DataValueField = "SupplierCode";
        SupplierDropDownList.DataTextField = "SupplierName";
        supplierList.Insert(0, new Supplier() { SupplierName = "Select Supplier", SupplierCode = "" });
        SupplierDropDownList.DataSource = supplierList;
        SupplierDropDownList.DataBind();
    }
}