//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS_Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentVoucher
    {
        public AdjustmentVoucher()
        {
            this.AdjustmentVoucherDetails = new HashSet<AdjustmentVoucherDetail>();
        }
    
        public int AvNo { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<int> IssueEmpNo { get; set; }
        public Nullable<int> ApproveEmpNo { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<AdjustmentVoucherDetail> AdjustmentVoucherDetails { get; set; }
    }
}
