
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LUSSIS_Backend
{

using System;
    using System.Collections.Generic;
    
public partial class Department
{

    public Department()
    {

        this.BackLogs = new HashSet<BackLog>();

        this.Disbursements = new HashSet<Disbursement>();

        this.Employees = new HashSet<Employee>();

        this.RetrievalDetails = new HashSet<RetrievalDetail>();

    }


    public string DeptCode { get; set; }

    public string DeptName { get; set; }

    public string ContactName { get; set; }

    public Nullable<decimal> PhoneNo { get; set; }

    public Nullable<decimal> FaxNo { get; set; }

    public Nullable<int> HeadEmpNo { get; set; }

    public Nullable<int> CollectionPointNo { get; set; }

    public Nullable<int> RepEmpNo { get; set; }

    public Nullable<int> DeputyEmpNo { get; set; }



    public virtual ICollection<BackLog> BackLogs { get; set; }

    public virtual CollectionPoint CollectionPoint { get; set; }

    public virtual Employee EmployeeHead { get; set; }

    public virtual Employee EmployeeRepresentative { get; set; }

    public virtual Employee EmployeeDeputy { get; set; }

    public virtual ICollection<Disbursement> Disbursements { get; set; }

    public virtual ICollection<Employee> Employees { get; set; }

    public virtual ICollection<RetrievalDetail> RetrievalDetails { get; set; }

}

}
