//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS_Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryCatalogue
    {
        public StationeryCatalogue()
        {
            this.AdjustmentVoucherDetails = new HashSet<AdjustmentVoucherDetail>();
            this.BackLogs = new HashSet<BackLog>();
            this.DisbursementDetails = new HashSet<DisbursementDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
            this.RetrievalDetails = new HashSet<RetrievalDetail>();
            this.StockTxnDetails = new HashSet<StockTxnDetail>();
            this.SupplyTenders = new HashSet<SupplyTender>();
        }
    
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Uom { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> CurrentQty { get; set; }
        public string Supplier1 { get; set; }
        public string Supplier2 { get; set; }
        public string Supplier3 { get; set; }
        public string Bin { get; set; }
    
        public virtual ICollection<AdjustmentVoucherDetail> AdjustmentVoucherDetails { get; set; }
        public virtual ICollection<BackLog> BackLogs { get; set; }
        public virtual ICollection<DisbursementDetail> DisbursementDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
        public virtual ICollection<RetrievalDetail> RetrievalDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier4 { get; set; }
        public virtual Supplier Supplier5 { get; set; }
        public virtual ICollection<StockTxnDetail> StockTxnDetails { get; set; }
        public virtual ICollection<SupplyTender> SupplyTenders { get; set; }
    }
}
