//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS_Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyTender
    {
        public string ItemNo { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual StationeryCatalogue StationeryCatalogue { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
